language: node_js
dist: xenial
os: linux
node_js:
  - node
  - lts/*
install:
  - npm ci
script:
  - npm run lint:sass
  - npm run lint:js
  - npm run production
deploy:
  strategy: git
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: dist
  on:
    branch: master
    node_js: 'lts/*'
